mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "password"
  database: "db"

rclone:

  # rclone host (without auth)
  host: "http://localhost:5572"

  # remote file system that previously configured on RClone,
  # for this example, s3 is the configuration name and mybucket is the s3 bucket name.
  fs: "s3:mybucket"

  # remote path
  remote: "db-backup"
